#define ACCESS_POINT "ArduinoAQI Setup"
#define THINGSPEAK_REGISTRY_CHANNEL_NUMBER 0
#define THINGSPEAK_REGISTRY_API_KEY ""
#define THINGSPEAK_RATE_LIMIT_SECONDS 30
#define DISPLAY_LENGTH 4
#define PIN_LED_CLK 14 // SCK D5 on WeMos D1 R2
#define PIN_LED_DIO 12 // MISO D6 on WeMos D1 R2
#define PIN_RESET 13 // MOSI D7 on WeMos D1 R2
#define PIN_PMS_TX 5 // SCL D1 on WeMos D1 R2
#define PIN_PMS_RX 4 // SDA D2 on WeMos D1 R2
