#define ACCESS_POINT "ArduinoAQI Setup"
#define THINGSPEAK_REGISTRY_CHANNEL_NUMBER 0
#define THINGSPEAK_REGISTRY_API_KEY ""
#define THINGSPEAK_RATE_LIMIT_SECONDS 15
#define DISPLAY_LENGTH 4
#define SPINUP_SECONDS 10
#define WIFI_VARIABLE_LENGTH 60
#define MAX_CONNECTION_ATTEMPTS 5
#define HOURS_TO_RESTART 6
#define MESSAGES_PER_YEAR 3000000
#define PIN_LED_CLK 14 // SCK D5 on WeMos D1 R2
#define PIN_LED_DIO 12 // MISO D6 on WeMos D1 R2
#define PIN_RESET 13 // MOSI D7 on WeMos D1 R2
#define PIN_PMS_TX 5 // SCL D1 on WeMos D1 R2
#define PIN_PMS_RX 4 // SDA D2 on WeMos D1 R2
